// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: games.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createGame = `-- name: CreateGame :one
INSERT INTO "Game" (
  "title",
  "publisher",
  "imagePath",
  "exePath",
  "saveFolderPath",
  "localSaveHash",
  "localSaveHashUpdatedAt",
  "totalPlayTime",
  "lastPlayed",
  "clearedAt"
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10
)
RETURNING
  "id",
  "title",
  "publisher",
  "imagePath",
  "exePath",
  "saveFolderPath",
  "createdAt",
  "updatedAt",
  "localSaveHash",
  "localSaveHashUpdatedAt",
  "totalPlayTime",
  "lastPlayed",
  "clearedAt"
`

type CreateGameParams struct {
	Title                  string         `json:"title"`
	Publisher              string         `json:"publisher"`
	ImagePath              sql.NullString `json:"image_path"`
	ExePath                string         `json:"exe_path"`
	SaveFolderPath         sql.NullString `json:"save_folder_path"`
	LocalSaveHash          sql.NullString `json:"local_save_hash"`
	LocalSaveHashUpdatedAt sql.NullTime   `json:"local_save_hash_updated_at"`
	TotalPlayTime          int64          `json:"total_play_time"`
	LastPlayed             sql.NullTime   `json:"last_played"`
	ClearedAt              sql.NullTime   `json:"cleared_at"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.Title,
		arg.Publisher,
		arg.ImagePath,
		arg.ExePath,
		arg.SaveFolderPath,
		arg.LocalSaveHash,
		arg.LocalSaveHashUpdatedAt,
		arg.TotalPlayTime,
		arg.LastPlayed,
		arg.ClearedAt,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Publisher,
		&i.ImagePath,
		&i.ExePath,
		&i.SaveFolderPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocalSaveHash,
		&i.LocalSaveHashUpdatedAt,
		&i.TotalPlayTime,
		&i.LastPlayed,
		&i.ClearedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM "Game"
WHERE "id" = ?1
`

func (q *Queries) DeleteGame(ctx context.Context, gameID string) error {
	_, err := q.db.ExecContext(ctx, deleteGame, gameID)
	return err
}

const getGameByExePath = `-- name: GetGameByExePath :one
SELECT
  "id",
  "title",
  "publisher",
  "imagePath",
  "exePath",
  "saveFolderPath",
  "createdAt",
  "updatedAt",
  "localSaveHash",
  "localSaveHashUpdatedAt",
  "totalPlayTime",
  "lastPlayed",
  "clearedAt"
FROM "Game"
WHERE lower("exePath") = lower(?1)
`

func (q *Queries) GetGameByExePath(ctx context.Context, exePath string) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByExePath, exePath)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Publisher,
		&i.ImagePath,
		&i.ExePath,
		&i.SaveFolderPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocalSaveHash,
		&i.LocalSaveHashUpdatedAt,
		&i.TotalPlayTime,
		&i.LastPlayed,
		&i.ClearedAt,
	)
	return i, err
}

const getGameByID = `-- name: GetGameByID :one
SELECT
  "id",
  "title",
  "publisher",
  "imagePath",
  "exePath",
  "saveFolderPath",
  "createdAt",
  "updatedAt",
  "localSaveHash",
  "localSaveHashUpdatedAt",
  "totalPlayTime",
  "lastPlayed",
  "clearedAt"
FROM "Game"
WHERE "id" = ?1
`

func (q *Queries) GetGameByID(ctx context.Context, gameID string) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByID, gameID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Publisher,
		&i.ImagePath,
		&i.ExePath,
		&i.SaveFolderPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocalSaveHash,
		&i.LocalSaveHashUpdatedAt,
		&i.TotalPlayTime,
		&i.LastPlayed,
		&i.ClearedAt,
	)
	return i, err
}

const touchGameUpdatedAt = `-- name: TouchGameUpdatedAt :exec
UPDATE "Game"
SET "updatedAt" = CURRENT_TIMESTAMP
WHERE "id" = ?1
`

func (q *Queries) TouchGameUpdatedAt(ctx context.Context, gameID string) error {
	_, err := q.db.ExecContext(ctx, touchGameUpdatedAt, gameID)
	return err
}

const updateGame = `-- name: UpdateGame :one
UPDATE "Game"
SET
  "title" = ?1,
  "publisher" = ?2,
  "imagePath" = ?3,
  "exePath" = ?4,
  "saveFolderPath" = ?5,
  "localSaveHash" = ?6,
  "localSaveHashUpdatedAt" = ?7,
  "totalPlayTime" = ?8,
  "lastPlayed" = ?9,
  "clearedAt" = ?10
WHERE "id" = ?11
RETURNING
  "id",
  "title",
  "publisher",
  "imagePath",
  "exePath",
  "saveFolderPath",
  "createdAt",
  "updatedAt",
  "localSaveHash",
  "localSaveHashUpdatedAt",
  "totalPlayTime",
  "lastPlayed",
  "clearedAt"
`

type UpdateGameParams struct {
	Title                  string         `json:"title"`
	Publisher              string         `json:"publisher"`
	ImagePath              sql.NullString `json:"image_path"`
	ExePath                string         `json:"exe_path"`
	SaveFolderPath         sql.NullString `json:"save_folder_path"`
	LocalSaveHash          sql.NullString `json:"local_save_hash"`
	LocalSaveHashUpdatedAt sql.NullTime   `json:"local_save_hash_updated_at"`
	TotalPlayTime          int64          `json:"total_play_time"`
	LastPlayed             sql.NullTime   `json:"last_played"`
	ClearedAt              sql.NullTime   `json:"cleared_at"`
	ID                     string         `json:"id"`
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, updateGame,
		arg.Title,
		arg.Publisher,
		arg.ImagePath,
		arg.ExePath,
		arg.SaveFolderPath,
		arg.LocalSaveHash,
		arg.LocalSaveHashUpdatedAt,
		arg.TotalPlayTime,
		arg.LastPlayed,
		arg.ClearedAt,
		arg.ID,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Publisher,
		&i.ImagePath,
		&i.ExePath,
		&i.SaveFolderPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocalSaveHash,
		&i.LocalSaveHashUpdatedAt,
		&i.TotalPlayTime,
		&i.LastPlayed,
		&i.ClearedAt,
	)
	return i, err
}

const upsertGameSync = `-- name: UpsertGameSync :exec
INSERT INTO "Game" (
  "id",
  "title",
  "publisher",
  "imagePath",
  "exePath",
  "saveFolderPath",
  "createdAt",
  "updatedAt",
  "localSaveHash",
  "localSaveHashUpdatedAt",
  "totalPlayTime",
  "lastPlayed",
  "clearedAt"
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13
)
ON CONFLICT("id") DO UPDATE SET
  "title" = excluded."title",
  "publisher" = excluded."publisher",
  "imagePath" = excluded."imagePath",
  "exePath" = excluded."exePath",
  "saveFolderPath" = excluded."saveFolderPath",
  "createdAt" = excluded."createdAt",
  "updatedAt" = excluded."updatedAt",
  "localSaveHash" = excluded."localSaveHash",
  "localSaveHashUpdatedAt" = excluded."localSaveHashUpdatedAt",
  "totalPlayTime" = excluded."totalPlayTime",
  "lastPlayed" = excluded."lastPlayed",
  "clearedAt" = excluded."clearedAt"
`

type UpsertGameSyncParams struct {
	ID                     string         `json:"id"`
	Title                  string         `json:"title"`
	Publisher              string         `json:"publisher"`
	ImagePath              sql.NullString `json:"image_path"`
	ExePath                string         `json:"exe_path"`
	SaveFolderPath         sql.NullString `json:"save_folder_path"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
	LocalSaveHash          sql.NullString `json:"local_save_hash"`
	LocalSaveHashUpdatedAt sql.NullTime   `json:"local_save_hash_updated_at"`
	TotalPlayTime          int64          `json:"total_play_time"`
	LastPlayed             sql.NullTime   `json:"last_played"`
	ClearedAt              sql.NullTime   `json:"cleared_at"`
}

func (q *Queries) UpsertGameSync(ctx context.Context, arg UpsertGameSyncParams) error {
	_, err := q.db.ExecContext(ctx, upsertGameSync,
		arg.ID,
		arg.Title,
		arg.Publisher,
		arg.ImagePath,
		arg.ExePath,
		arg.SaveFolderPath,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LocalSaveHash,
		arg.LocalSaveHashUpdatedAt,
		arg.TotalPlayTime,
		arg.LastPlayed,
		arg.ClearedAt,
	)
	return err
}
