// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Game struct {
	ID                     string         `json:"id"`
	Title                  string         `json:"title"`
	Publisher              string         `json:"publisher"`
	ImagePath              sql.NullString `json:"imagePath"`
	ExePath                string         `json:"exePath"`
	SaveFolderPath         sql.NullString `json:"saveFolderPath"`
	CreatedAt              time.Time      `json:"createdAt"`
	UpdatedAt              time.Time      `json:"updatedAt"`
	LocalSaveHash          sql.NullString `json:"localSaveHash"`
	LocalSaveHashUpdatedAt sql.NullTime   `json:"localSaveHashUpdatedAt"`
	TotalPlayTime          int64          `json:"totalPlayTime"`
	LastPlayed             sql.NullTime   `json:"lastPlayed"`
	ClearedAt              sql.NullTime   `json:"clearedAt"`
}

type Memo struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	GameId    string    `json:"gameId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type PlayRoute struct {
	ID        string    `json:"id"`
	GameId    string    `json:"gameId"`
	Name      string    `json:"name"`
	SortOrder int64     `json:"sortOrder"`
	CreatedAt time.Time `json:"createdAt"`
}

type PlaySession struct {
	ID          string         `json:"id"`
	GameId      string         `json:"gameId"`
	PlayRouteId sql.NullString `json:"playRouteId"`
	PlayedAt    time.Time      `json:"playedAt"`
	Duration    int64          `json:"duration"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}
