// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: play_sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createPlaySession = `-- name: CreatePlaySession :one
INSERT INTO "PlaySession" (
  "gameId",
  "playRouteId",
  "playedAt",
  "duration"
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4
)
RETURNING
  "id",
  "gameId",
  "playRouteId",
  "playedAt",
  "duration",
  "updatedAt"
`

type CreatePlaySessionParams struct {
	GameID      string         `json:"game_id"`
	PlayRouteID sql.NullString `json:"play_route_id"`
	PlayedAt    time.Time      `json:"played_at"`
	Duration    int64          `json:"duration"`
}

func (q *Queries) CreatePlaySession(ctx context.Context, arg CreatePlaySessionParams) (PlaySession, error) {
	row := q.db.QueryRowContext(ctx, createPlaySession,
		arg.GameID,
		arg.PlayRouteID,
		arg.PlayedAt,
		arg.Duration,
	)
	var i PlaySession
	err := row.Scan(
		&i.ID,
		&i.GameId,
		&i.PlayRouteId,
		&i.PlayedAt,
		&i.Duration,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlaySession = `-- name: DeletePlaySession :exec
DELETE FROM "PlaySession"
WHERE "id" = ?1
`

func (q *Queries) DeletePlaySession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deletePlaySession, sessionID)
	return err
}

const deletePlaySessionsByGame = `-- name: DeletePlaySessionsByGame :exec
DELETE FROM "PlaySession"
WHERE "gameId" = ?1
`

func (q *Queries) DeletePlaySessionsByGame(ctx context.Context, gameID string) error {
	_, err := q.db.ExecContext(ctx, deletePlaySessionsByGame, gameID)
	return err
}

const getPlaySessionByID = `-- name: GetPlaySessionByID :one
SELECT
  "id",
  "gameId",
  "playRouteId",
  "playedAt",
  "duration",
  "updatedAt"
FROM "PlaySession"
WHERE "id" = ?1
`

func (q *Queries) GetPlaySessionByID(ctx context.Context, sessionID string) (PlaySession, error) {
	row := q.db.QueryRowContext(ctx, getPlaySessionByID, sessionID)
	var i PlaySession
	err := row.Scan(
		&i.ID,
		&i.GameId,
		&i.PlayRouteId,
		&i.PlayedAt,
		&i.Duration,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlaySessionsByGame = `-- name: ListPlaySessionsByGame :many
SELECT
  "id",
  "gameId",
  "playRouteId",
  "playedAt",
  "duration",
  "updatedAt"
FROM "PlaySession"
WHERE "gameId" = ?1
ORDER BY "playedAt" DESC
`

func (q *Queries) ListPlaySessionsByGame(ctx context.Context, gameID string) ([]PlaySession, error) {
	rows, err := q.db.QueryContext(ctx, listPlaySessionsByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaySession
	for rows.Next() {
		var i PlaySession
		if err := rows.Scan(
			&i.ID,
			&i.GameId,
			&i.PlayRouteId,
			&i.PlayedAt,
			&i.Duration,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlaySessionSync = `-- name: UpsertPlaySessionSync :exec
INSERT INTO "PlaySession" (
  "id",
  "gameId",
  "playRouteId",
  "playedAt",
  "duration",
  "updatedAt"
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6
)
ON CONFLICT("id") DO UPDATE SET
  "gameId" = excluded."gameId",
  "playRouteId" = excluded."playRouteId",
  "playedAt" = excluded."playedAt",
  "duration" = excluded."duration",
  "updatedAt" = excluded."updatedAt"
`

type UpsertPlaySessionSyncParams struct {
	ID          string         `json:"id"`
	GameID      string         `json:"game_id"`
	PlayRouteID sql.NullString `json:"play_route_id"`
	PlayedAt    time.Time      `json:"played_at"`
	Duration    int64          `json:"duration"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) UpsertPlaySessionSync(ctx context.Context, arg UpsertPlaySessionSyncParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlaySessionSync,
		arg.ID,
		arg.GameID,
		arg.PlayRouteID,
		arg.PlayedAt,
		arg.Duration,
		arg.UpdatedAt,
	)
	return err
}
