// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: play_routes.sql

package sqlc

import (
	"context"
	"time"
)

const createPlayRoute = `-- name: CreatePlayRoute :one
INSERT INTO "PlayRoute" (
  "gameId",
  "name",
  "sortOrder"
) VALUES (
  ?1,
  ?2,
  ?3
)
RETURNING
  "id",
  "gameId",
  "name",
  "sortOrder",
  "createdAt"
`

type CreatePlayRouteParams struct {
	GameID    string `json:"game_id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) CreatePlayRoute(ctx context.Context, arg CreatePlayRouteParams) (PlayRoute, error) {
	row := q.db.QueryRowContext(ctx, createPlayRoute, arg.GameID, arg.Name, arg.SortOrder)
	var i PlayRoute
	err := row.Scan(
		&i.ID,
		&i.GameId,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlayRoute = `-- name: DeletePlayRoute :exec
DELETE FROM "PlayRoute"
WHERE "id" = ?1
`

func (q *Queries) DeletePlayRoute(ctx context.Context, routeID string) error {
	_, err := q.db.ExecContext(ctx, deletePlayRoute, routeID)
	return err
}

const deletePlayRoutesByGame = `-- name: DeletePlayRoutesByGame :exec
DELETE FROM "PlayRoute"
WHERE "gameId" = ?1
`

func (q *Queries) DeletePlayRoutesByGame(ctx context.Context, gameID string) error {
	_, err := q.db.ExecContext(ctx, deletePlayRoutesByGame, gameID)
	return err
}

const listPlayRoutesByGame = `-- name: ListPlayRoutesByGame :many
SELECT
  "id",
  "gameId",
  "name",
  "sortOrder",
  "createdAt"
FROM "PlayRoute"
WHERE "gameId" = ?1
ORDER BY "sortOrder" ASC, "createdAt" ASC
`

func (q *Queries) ListPlayRoutesByGame(ctx context.Context, gameID string) ([]PlayRoute, error) {
	rows, err := q.db.QueryContext(ctx, listPlayRoutesByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayRoute
	for rows.Next() {
		var i PlayRoute
		if err := rows.Scan(
			&i.ID,
			&i.GameId,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayRouteSync = `-- name: UpsertPlayRouteSync :exec
INSERT INTO "PlayRoute" (
  "id",
  "gameId",
  "name",
  "sortOrder",
  "createdAt"
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5
)
ON CONFLICT("id") DO UPDATE SET
  "gameId" = excluded."gameId",
  "name" = excluded."name",
  "sortOrder" = excluded."sortOrder",
  "createdAt" = excluded."createdAt"
`

type UpsertPlayRouteSyncParams struct {
	ID        string    `json:"id"`
	GameID    string    `json:"game_id"`
	Name      string    `json:"name"`
	SortOrder int64     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) UpsertPlayRouteSync(ctx context.Context, arg UpsertPlayRouteSyncParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayRouteSync,
		arg.ID,
		arg.GameID,
		arg.Name,
		arg.SortOrder,
		arg.CreatedAt,
	)
	return err
}
