// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreatePlayRoute(ctx context.Context, arg CreatePlayRouteParams) (PlayRoute, error)
	CreatePlaySession(ctx context.Context, arg CreatePlaySessionParams) (PlaySession, error)
	DeleteGame(ctx context.Context, gameID string) error
	DeletePlayRoute(ctx context.Context, routeID string) error
	DeletePlayRoutesByGame(ctx context.Context, gameID string) error
	DeletePlaySession(ctx context.Context, sessionID string) error
	DeletePlaySessionsByGame(ctx context.Context, gameID string) error
	GetGameByExePath(ctx context.Context, exePath string) (Game, error)
	GetGameByID(ctx context.Context, gameID string) (Game, error)
	GetPlaySessionByID(ctx context.Context, sessionID string) (PlaySession, error)
	ListPlayRoutesByGame(ctx context.Context, gameID string) ([]PlayRoute, error)
	ListPlaySessionsByGame(ctx context.Context, gameID string) ([]PlaySession, error)
	TouchGameUpdatedAt(ctx context.Context, gameID string) error
	UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error)
	UpsertGameSync(ctx context.Context, arg UpsertGameSyncParams) error
	UpsertPlayRouteSync(ctx context.Context, arg UpsertPlayRouteSyncParams) error
	UpsertPlaySessionSync(ctx context.Context, arg UpsertPlaySessionSyncParams) error
}

var _ Querier = (*Queries)(nil)
