// @fileoverview メモファイルの作成・更新・削除を提供する。
package memo

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// FileManager はメモファイルの管理を担当する。
type FileManager struct {
	baseDir string
}

// NewFileManager は FileManager を作成する。
func NewFileManager(appDataDir string) *FileManager {
	return &FileManager{baseDir: filepath.Join(appDataDir, "memos")}
}

// EnsureBaseDir はベースディレクトリを作成する。
func (manager *FileManager) EnsureBaseDir() error {
	return os.MkdirAll(manager.baseDir, 0o700)
}

// RootDir はメモのルートディレクトリを返す。
func (manager *FileManager) RootDir() string {
	return manager.baseDir
}

// GameDir はゲームIDに対応するディレクトリを返す。
func (manager *FileManager) GameDir(gameID string) string {
	return filepath.Join(manager.baseDir, sanitizeFileName(gameID))
}

// MemoFilePath はメモファイルのパスを返す。
func (manager *FileManager) MemoFilePath(gameID string, memoID string, title string) string {
	fileName := fmt.Sprintf("%s_%s.md", sanitizeFileName(title), memoID)
	return filepath.Join(manager.GameDir(gameID), fileName)
}

// CreateMemoFile はメモファイルを作成する。
func (manager *FileManager) CreateMemoFile(gameID string, memoID string, title string, content string) (string, error) {
	if error := manager.EnsureBaseDir(); error != nil {
		return "", error
	}
	gameDir := manager.GameDir(gameID)
	if error := os.MkdirAll(gameDir, 0o700); error != nil {
		return "", error
	}
	path := manager.MemoFilePath(gameID, memoID, title)
	payload := GenerateLocalMemoFileContent(title, content)
	return path, os.WriteFile(path, []byte(payload), 0o600)
}

// UpdateMemoFile はメモファイルを更新する。
func (manager *FileManager) UpdateMemoFile(gameID string, memoID string, oldTitle string, newTitle string, content string) (string, error) {
	if error := manager.EnsureBaseDir(); error != nil {
		return "", error
	}
	if error := os.MkdirAll(manager.GameDir(gameID), 0o700); error != nil {
		return "", error
	}
	oldPath := manager.MemoFilePath(gameID, memoID, oldTitle)
	newPath := manager.MemoFilePath(gameID, memoID, newTitle)
	payload := GenerateLocalMemoFileContent(newTitle, content)
	if error := os.WriteFile(newPath, []byte(payload), 0o600); error != nil {
		return "", error
	}
	if oldTitle != newTitle {
		_ = os.Remove(oldPath)
	}
	return newPath, nil
}

// DeleteMemoFile はメモファイルを削除する。
func (manager *FileManager) DeleteMemoFile(gameID string, memoID string, title string) error {
	path := manager.MemoFilePath(gameID, memoID, title)
	return os.Remove(path)
}

// DeleteGameMemoFiles はゲーム配下のメモを削除する。
func (manager *FileManager) DeleteGameMemoFiles(gameID string) error {
	return os.RemoveAll(manager.GameDir(gameID))
}

// GenerateLocalMemoFileContent はローカル保存用のメモ内容を生成する。
func GenerateLocalMemoFileContent(title string, content string) string {
	timestamp := time.Now().UTC().Format(time.RFC3339)
	return fmt.Sprintf(`# %s

<!-- Created: %s -->
<!-- Generated by CloudLaunch -->

%s
`, title, timestamp, content)
}

// GenerateCloudMemoFileContent はクラウド保存用のメモ内容を生成する。
func GenerateCloudMemoFileContent(title string, content string, gameTitle string) string {
	timestamp := time.Now().UTC().Format(time.RFC3339)
	return fmt.Sprintf(`# %s

<!-- Created: %s -->
<!-- Generated by CloudLaunch -->
<!-- Game: %s -->

%s
`, title, timestamp, gameTitle, content)
}

// ExtractMemoContent はメモファイルから本文を抽出する。
func ExtractMemoContent(fileContent string) string {
	lines := strings.Split(fileContent, "\n")
	contentLines := make([]string, 0, len(lines))
	foundContent := false
	for _, line := range lines {
		if strings.HasPrefix(line, "#") && !foundContent {
			continue
		}
		if strings.HasPrefix(line, "<!--") || strings.HasPrefix(line, "-->") {
			continue
		}
		if strings.TrimSpace(line) == "" && !foundContent {
			continue
		}
		foundContent = true
		contentLines = append(contentLines, line)
	}
	return strings.TrimSpace(strings.Join(contentLines, "\n"))
}

// sanitizeFileName はローカルファイル名を安全化する。
func sanitizeFileName(name string) string {
	replacer := strings.NewReplacer("<", "_", ">", "_", ":", "_", "\"", "_", "/", "_", "\\", "_", "|", "_", "?", "_", "*", "_")
	sanitized := replacer.Replace(strings.TrimSpace(name))
	sanitized = strings.ReplaceAll(sanitized, " ", "_")
	if len(sanitized) > 100 {
		sanitized = sanitized[:100]
	}
	return sanitized
}
