ALTER TABLE "Game" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "PlaySession" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TRIGGER IF NOT EXISTS "trigger_game_updated_at"
AFTER UPDATE ON "Game"
FOR EACH ROW
BEGIN
  UPDATE "Game" SET "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = OLD."id";
END;

CREATE TRIGGER IF NOT EXISTS "trigger_play_session_updated_at"
AFTER UPDATE ON "PlaySession"
FOR EACH ROW
BEGIN
  UPDATE "PlaySession" SET "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = OLD."id";
END;
