// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDirectoryExists(arg1, arg2) {
  return window['go']['app']['App']['CheckDirectoryExists'](arg1, arg2);
}

export function CheckFileExists(arg1, arg2) {
  return window['go']['app']['App']['CheckFileExists'](arg1, arg2);
}

export function CreateChapter(arg1, arg2) {
  return window['go']['app']['App']['CreateChapter'](arg1, arg2);
}

export function CreateGame(arg1, arg2) {
  return window['go']['app']['App']['CreateGame'](arg1, arg2);
}

export function CreateMemo(arg1, arg2) {
  return window['go']['app']['App']['CreateMemo'](arg1, arg2);
}

export function CreateSession(arg1, arg2) {
  return window['go']['app']['App']['CreateSession'](arg1, arg2);
}

export function CreateUpload(arg1, arg2) {
  return window['go']['app']['App']['CreateUpload'](arg1, arg2);
}

export function DeleteChapter(arg1, arg2) {
  return window['go']['app']['App']['DeleteChapter'](arg1, arg2);
}

export function DeleteCloudData(arg1, arg2) {
  return window['go']['app']['App']['DeleteCloudData'](arg1, arg2);
}

export function DeleteCredential(arg1, arg2) {
  return window['go']['app']['App']['DeleteCredential'](arg1, arg2);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['app']['App']['DeleteFile'](arg1, arg2);
}

export function DeleteGame(arg1, arg2) {
  return window['go']['app']['App']['DeleteGame'](arg1, arg2);
}

export function DeleteMemo(arg1, arg2) {
  return window['go']['app']['App']['DeleteMemo'](arg1, arg2);
}

export function DeleteSession(arg1, arg2) {
  return window['go']['app']['App']['DeleteSession'](arg1, arg2);
}

export function DownloadMemoFromCloud(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadMemoFromCloud'](arg1, arg2, arg3);
}

export function DownloadSaveData(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadSaveData'](arg1, arg2, arg3);
}

export function GetChapterStats(arg1, arg2) {
  return window['go']['app']['App']['GetChapterStats'](arg1, arg2);
}

export function GetCloudFileDetails(arg1, arg2) {
  return window['go']['app']['App']['GetCloudFileDetails'](arg1, arg2);
}

export function GetCloudFileDetailsByGame(arg1, arg2) {
  return window['go']['app']['App']['GetCloudFileDetailsByGame'](arg1, arg2);
}

export function GetCloudMemos(arg1) {
  return window['go']['app']['App']['GetCloudMemos'](arg1);
}

export function GetDirectoryTree(arg1) {
  return window['go']['app']['App']['GetDirectoryTree'](arg1);
}

export function GetGameByID(arg1, arg2) {
  return window['go']['app']['App']['GetGameByID'](arg1, arg2);
}

export function GetGameMemoDir(arg1, arg2) {
  return window['go']['app']['App']['GetGameMemoDir'](arg1, arg2);
}

export function GetMemoByID(arg1, arg2) {
  return window['go']['app']['App']['GetMemoByID'](arg1, arg2);
}

export function GetMemoFilePath(arg1, arg2) {
  return window['go']['app']['App']['GetMemoFilePath'](arg1, arg2);
}

export function GetMemoRootDir(arg1) {
  return window['go']['app']['App']['GetMemoRootDir'](arg1);
}

export function GetMonitoringStatus(arg1) {
  return window['go']['app']['App']['GetMonitoringStatus'](arg1);
}

export function LaunchGame(arg1, arg2) {
  return window['go']['app']['App']['LaunchGame'](arg1, arg2);
}

export function ListAllMemos(arg1) {
  return window['go']['app']['App']['ListAllMemos'](arg1);
}

export function ListChaptersByGame(arg1, arg2) {
  return window['go']['app']['App']['ListChaptersByGame'](arg1, arg2);
}

export function ListCloudData(arg1) {
  return window['go']['app']['App']['ListCloudData'](arg1);
}

export function ListGames(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ListGames'](arg1, arg2, arg3, arg4, arg5);
}

export function ListMemosByGame(arg1, arg2) {
  return window['go']['app']['App']['ListMemosByGame'](arg1, arg2);
}

export function ListSessionsByGame(arg1, arg2) {
  return window['go']['app']['App']['ListSessionsByGame'](arg1, arg2);
}

export function ListUploadsByGame(arg1, arg2) {
  return window['go']['app']['App']['ListUploadsByGame'](arg1, arg2);
}

export function LoadCloudMetadata(arg1, arg2) {
  return window['go']['app']['App']['LoadCloudMetadata'](arg1, arg2);
}

export function LoadCredential(arg1, arg2) {
  return window['go']['app']['App']['LoadCredential'](arg1, arg2);
}

export function LoadImageFromLocal(arg1, arg2) {
  return window['go']['app']['App']['LoadImageFromLocal'](arg1, arg2);
}

export function OpenFolder(arg1, arg2) {
  return window['go']['app']['App']['OpenFolder'](arg1, arg2);
}

export function OpenLogsDirectory(arg1) {
  return window['go']['app']['App']['OpenLogsDirectory'](arg1);
}

export function SaveCloudMetadata(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveCloudMetadata'](arg1, arg2, arg3);
}

export function SaveCredential(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveCredential'](arg1, arg2, arg3);
}

export function SelectFile(arg1, arg2) {
  return window['go']['app']['App']['SelectFile'](arg1, arg2);
}

export function SelectFolder(arg1) {
  return window['go']['app']['App']['SelectFolder'](arg1);
}

export function SetCurrentChapter(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetCurrentChapter'](arg1, arg2, arg3);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function SyncMemosFromCloud(arg1, arg2) {
  return window['go']['app']['App']['SyncMemosFromCloud'](arg1, arg2);
}

export function UpdateAutoTracking(arg1, arg2) {
  return window['go']['app']['App']['UpdateAutoTracking'](arg1, arg2);
}

export function UpdateChapter(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateChapter'](arg1, arg2, arg3);
}

export function UpdateChapterOrders(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateChapterOrders'](arg1, arg2, arg3);
}

export function UpdateGame(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateGame'](arg1, arg2, arg3);
}

export function UpdateMemo(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateMemo'](arg1, arg2, arg3);
}

export function UpdatePlayTime(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdatePlayTime'](arg1, arg2, arg3, arg4);
}

export function UpdateSessionChapter(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateSessionChapter'](arg1, arg2, arg3);
}

export function UpdateSessionName(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateSessionName'](arg1, arg2, arg3);
}

export function UploadFolder(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UploadFolder'](arg1, arg2, arg3, arg4);
}

export function UploadMemoToCloud(arg1, arg2) {
  return window['go']['app']['App']['UploadMemoToCloud'](arg1, arg2);
}

export function ValidateCredential(arg1, arg2) {
  return window['go']['app']['App']['ValidateCredential'](arg1, arg2);
}
