// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {result} from '../models';
import {services} from '../models';
import {storage} from '../models';
import {app} from '../models';
import {context} from '../models';
import {time} from '../models';

export function CheckDirectoryExists(arg1:string):Promise<result.ApiResult_bool_>;

export function CheckFileExists(arg1:string):Promise<result.ApiResult_bool_>;

export function CreateChapter(arg1:services.ChapterInput):Promise<result.ApiResult_CloudLaunch_Go_internal_models_Chapter_>;

export function CreateGame(arg1:services.GameInput):Promise<result.ApiResult_CloudLaunch_Go_internal_models_Game_>;

export function CreateMemo(arg1:services.MemoInput):Promise<result.ApiResult_CloudLaunch_Go_internal_models_Memo_>;

export function CreateSession(arg1:services.SessionInput):Promise<result.ApiResult_CloudLaunch_Go_internal_models_PlaySession_>;

export function CreateUpload(arg1:services.UploadInput):Promise<result.ApiResult_CloudLaunch_Go_internal_models_Upload_>;

export function DeleteChapter(arg1:string):Promise<result.ApiResult_bool_>;

export function DeleteCloudData(arg1:string):Promise<result.ApiResult_bool_>;

export function DeleteCredential(arg1:string):Promise<result.ApiResult_bool_>;

export function DeleteFile(arg1:string):Promise<result.ApiResult_bool_>;

export function DeleteGame(arg1:string):Promise<result.ApiResult_bool_>;

export function DeleteMemo(arg1:string):Promise<result.ApiResult_bool_>;

export function DeleteSession(arg1:string):Promise<result.ApiResult_bool_>;

export function DownloadMemoFromCloud(arg1:string,arg2:string):Promise<result.ApiResult_string_>;

export function DownloadSaveData(arg1:string,arg2:string):Promise<result.ApiResult_bool_>;

export function GetChapterStats(arg1:string):Promise<result.ApiResult___CloudLaunch_Go_internal_models_ChapterStat_>;

export function GetCloudFileDetails(arg1:string):Promise<result.ApiResult___CloudLaunch_Go_internal_app_CloudFileDetail_>;

export function GetCloudFileDetailsByGame(arg1:string):Promise<result.ApiResult_CloudLaunch_Go_internal_app_CloudFileDetailsResult_>;

export function GetCloudMemos():Promise<result.ApiResult___CloudLaunch_Go_internal_app_CloudMemoInfo_>;

export function GetDirectoryTree():Promise<result.ApiResult___CloudLaunch_Go_internal_app_CloudDirectoryNode_>;

export function GetGameByID(arg1:string):Promise<result.ApiResult_CloudLaunch_Go_internal_models_Game_>;

export function GetGameMemoDir(arg1:string):Promise<result.ApiResult_string_>;

export function GetMemoByID(arg1:string):Promise<result.ApiResult_CloudLaunch_Go_internal_models_Memo_>;

export function GetMemoFilePath(arg1:string):Promise<result.ApiResult_string_>;

export function GetMemoRootDir():Promise<result.ApiResult_string_>;

export function GetMonitoringStatus():Promise<result.ApiResult___CloudLaunch_Go_internal_models_MonitoringGameStatus_>;

export function GetProcessSnapshot():Promise<result.ApiResult_CloudLaunch_Go_internal_models_ProcessSnapshot_>;

export function LaunchGame(arg1:string):Promise<result.ApiResult_bool_>;

export function ListAllMemos():Promise<result.ApiResult___CloudLaunch_Go_internal_models_Memo_>;

export function ListChaptersByGame(arg1:string):Promise<result.ApiResult___CloudLaunch_Go_internal_models_Chapter_>;

export function ListCloudData():Promise<result.ApiResult___CloudLaunch_Go_internal_app_CloudDataItem_>;

export function ListGames(arg1:string,arg2:string,arg3:string,arg4:string):Promise<result.ApiResult___CloudLaunch_Go_internal_models_Game_>;

export function ListMemosByGame(arg1:string):Promise<result.ApiResult___CloudLaunch_Go_internal_models_Memo_>;

export function ListSessionsByGame(arg1:string):Promise<result.ApiResult___CloudLaunch_Go_internal_models_PlaySession_>;

export function ListUploadsByGame(arg1:string):Promise<result.ApiResult___CloudLaunch_Go_internal_models_Upload_>;

export function LoadCloudMetadata(arg1:string):Promise<result.ApiResult_CloudLaunch_Go_internal_storage_CloudMetadata_>;

export function LoadCredential(arg1:string):Promise<result.ApiResult_CloudLaunch_Go_internal_services_CredentialOutput_>;

export function LoadImageFromLocal(arg1:string):Promise<result.ApiResult_string_>;

export function OpenFolder(arg1:string):Promise<result.ApiResult_bool_>;

export function OpenLogsDirectory():Promise<result.ApiResult_string_>;

export function SaveCloudMetadata(arg1:string,arg2:storage.CloudMetadata):Promise<result.ApiResult_bool_>;

export function SaveCredential(arg1:string,arg2:services.CredentialInput):Promise<result.ApiResult_bool_>;

export function SelectFile(arg1:Array<app.FileFilterInput>):Promise<result.ApiResult_string_>;

export function SelectFolder():Promise<result.ApiResult_string_>;

export function SetCurrentChapter(arg1:string,arg2:string):Promise<result.ApiResult_bool_>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function SyncMemosFromCloud(arg1:string):Promise<result.ApiResult_CloudLaunch_Go_internal_app_MemoSyncResult_>;

export function UpdateAutoTracking(arg1:boolean):Promise<result.ApiResult_bool_>;

export function UpdateChapter(arg1:string,arg2:services.ChapterUpdateInput):Promise<result.ApiResult_CloudLaunch_Go_internal_models_Chapter_>;

export function UpdateChapterOrders(arg1:string,arg2:Array<services.ChapterOrderUpdate>):Promise<result.ApiResult_bool_>;

export function UpdateGame(arg1:string,arg2:services.GameUpdateInput):Promise<result.ApiResult_CloudLaunch_Go_internal_models_Game_>;

export function UpdateMemo(arg1:string,arg2:services.MemoUpdateInput):Promise<result.ApiResult_CloudLaunch_Go_internal_models_Memo_>;

export function UpdatePlayTime(arg1:string,arg2:number,arg3:time.Time):Promise<result.ApiResult_CloudLaunch_Go_internal_models_Game_>;

export function UpdateSessionChapter(arg1:string,arg2:any):Promise<result.ApiResult_bool_>;

export function UpdateSessionName(arg1:string,arg2:string):Promise<result.ApiResult_bool_>;

export function UploadFolder(arg1:string,arg2:string,arg3:string):Promise<result.ApiResult_CloudLaunch_Go_internal_storage_UploadSummary_>;

export function UploadMemoToCloud(arg1:string):Promise<result.ApiResult_bool_>;

export function ValidateCredential(arg1:app.CredentialValidationInput):Promise<result.ApiResult_bool_>;

export function ValidateSavedCredential(arg1:string):Promise<result.ApiResult_bool_>;
