// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDirectoryExists(arg1) {
  return window['go']['app']['App']['CheckDirectoryExists'](arg1);
}

export function CheckFileExists(arg1) {
  return window['go']['app']['App']['CheckFileExists'](arg1);
}

export function CreateChapter(arg1) {
  return window['go']['app']['App']['CreateChapter'](arg1);
}

export function CreateGame(arg1) {
  return window['go']['app']['App']['CreateGame'](arg1);
}

export function CreateMemo(arg1) {
  return window['go']['app']['App']['CreateMemo'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['app']['App']['CreateSession'](arg1);
}

export function CreateUpload(arg1) {
  return window['go']['app']['App']['CreateUpload'](arg1);
}

export function DeleteChapter(arg1) {
  return window['go']['app']['App']['DeleteChapter'](arg1);
}

export function DeleteCloudData(arg1) {
  return window['go']['app']['App']['DeleteCloudData'](arg1);
}

export function DeleteCredential(arg1) {
  return window['go']['app']['App']['DeleteCredential'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['app']['App']['DeleteFile'](arg1);
}

export function DeleteGame(arg1) {
  return window['go']['app']['App']['DeleteGame'](arg1);
}

export function DeleteMemo(arg1) {
  return window['go']['app']['App']['DeleteMemo'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['app']['App']['DeleteSession'](arg1);
}

export function DownloadMemoFromCloud(arg1, arg2) {
  return window['go']['app']['App']['DownloadMemoFromCloud'](arg1, arg2);
}

export function DownloadSaveData(arg1, arg2) {
  return window['go']['app']['App']['DownloadSaveData'](arg1, arg2);
}

export function GetChapterStats(arg1) {
  return window['go']['app']['App']['GetChapterStats'](arg1);
}

export function GetCloudFileDetails(arg1) {
  return window['go']['app']['App']['GetCloudFileDetails'](arg1);
}

export function GetCloudFileDetailsByGame(arg1) {
  return window['go']['app']['App']['GetCloudFileDetailsByGame'](arg1);
}

export function GetCloudMemos() {
  return window['go']['app']['App']['GetCloudMemos']();
}

export function GetDirectoryTree() {
  return window['go']['app']['App']['GetDirectoryTree']();
}

export function GetGameByID(arg1) {
  return window['go']['app']['App']['GetGameByID'](arg1);
}

export function GetGameMemoDir(arg1) {
  return window['go']['app']['App']['GetGameMemoDir'](arg1);
}

export function GetMemoByID(arg1) {
  return window['go']['app']['App']['GetMemoByID'](arg1);
}

export function GetMemoFilePath(arg1) {
  return window['go']['app']['App']['GetMemoFilePath'](arg1);
}

export function GetMemoRootDir() {
  return window['go']['app']['App']['GetMemoRootDir']();
}

export function GetMonitoringStatus() {
  return window['go']['app']['App']['GetMonitoringStatus']();
}

export function GetProcessSnapshot() {
  return window['go']['app']['App']['GetProcessSnapshot']();
}

export function LaunchGame(arg1) {
  return window['go']['app']['App']['LaunchGame'](arg1);
}

export function ListAllMemos() {
  return window['go']['app']['App']['ListAllMemos']();
}

export function ListChaptersByGame(arg1) {
  return window['go']['app']['App']['ListChaptersByGame'](arg1);
}

export function ListCloudData() {
  return window['go']['app']['App']['ListCloudData']();
}

export function ListGames(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListGames'](arg1, arg2, arg3, arg4);
}

export function ListMemosByGame(arg1) {
  return window['go']['app']['App']['ListMemosByGame'](arg1);
}

export function ListSessionsByGame(arg1) {
  return window['go']['app']['App']['ListSessionsByGame'](arg1);
}

export function ListUploadsByGame(arg1) {
  return window['go']['app']['App']['ListUploadsByGame'](arg1);
}

export function LoadCloudMetadata(arg1) {
  return window['go']['app']['App']['LoadCloudMetadata'](arg1);
}

export function LoadCredential(arg1) {
  return window['go']['app']['App']['LoadCredential'](arg1);
}

export function LoadImageFromLocal(arg1) {
  return window['go']['app']['App']['LoadImageFromLocal'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['app']['App']['OpenFolder'](arg1);
}

export function OpenLogsDirectory() {
  return window['go']['app']['App']['OpenLogsDirectory']();
}

export function SaveCloudMetadata(arg1, arg2) {
  return window['go']['app']['App']['SaveCloudMetadata'](arg1, arg2);
}

export function SaveCredential(arg1, arg2) {
  return window['go']['app']['App']['SaveCredential'](arg1, arg2);
}

export function SelectFile(arg1) {
  return window['go']['app']['App']['SelectFile'](arg1);
}

export function SelectFolder() {
  return window['go']['app']['App']['SelectFolder']();
}

export function SetCurrentChapter(arg1, arg2) {
  return window['go']['app']['App']['SetCurrentChapter'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function SyncMemosFromCloud(arg1) {
  return window['go']['app']['App']['SyncMemosFromCloud'](arg1);
}

export function UpdateAutoTracking(arg1) {
  return window['go']['app']['App']['UpdateAutoTracking'](arg1);
}

export function UpdateUploadConcurrency(arg1) {
  return window['go']['app']['App']['UpdateUploadConcurrency'](arg1);
}

export function UpdateChapter(arg1, arg2) {
  return window['go']['app']['App']['UpdateChapter'](arg1, arg2);
}

export function UpdateChapterOrders(arg1, arg2) {
  return window['go']['app']['App']['UpdateChapterOrders'](arg1, arg2);
}

export function UpdateGame(arg1, arg2) {
  return window['go']['app']['App']['UpdateGame'](arg1, arg2);
}

export function UpdateMemo(arg1, arg2) {
  return window['go']['app']['App']['UpdateMemo'](arg1, arg2);
}

export function UpdatePlayTime(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdatePlayTime'](arg1, arg2, arg3);
}

export function UpdateSessionChapter(arg1, arg2) {
  return window['go']['app']['App']['UpdateSessionChapter'](arg1, arg2);
}

export function UpdateSessionName(arg1, arg2) {
  return window['go']['app']['App']['UpdateSessionName'](arg1, arg2);
}

export function UploadFolder(arg1, arg2, arg3) {
  return window['go']['app']['App']['UploadFolder'](arg1, arg2, arg3);
}

export function UploadMemoToCloud(arg1) {
  return window['go']['app']['App']['UploadMemoToCloud'](arg1);
}

export function ValidateCredential(arg1) {
  return window['go']['app']['App']['ValidateCredential'](arg1);
}

export function ValidateSavedCredential(arg1) {
  return window['go']['app']['App']['ValidateSavedCredential'](arg1);
}
