# Wails の production ビルド前に、コミットIDとスクリーンショット取得ツールを準備する。

& "$PSScriptRoot/fetch-screencap-cli.ps1"
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$revision = (git -C $repoRoot rev-parse --verify HEAD).Trim()
if ($LASTEXITCODE -ne 0 -or $revision -notmatch '^[0-9a-f]{40}$') {
    throw "ビルド用コミットIDを取得できませんでした"
}

$outputPath = Join-Path $repoRoot 'internal/buildinfo/revision_production.go'
$source = "// Code generated by scripts/prepare-build.ps1; DO NOT EDIT.`n" +
    "//go:build production`n`n" +
    "package buildinfo`n`n" +
    "func generatedRevision() string { return `"$revision`" }`n"
[System.IO.File]::WriteAllText($outputPath, $source, [System.Text.UTF8Encoding]::new($false))
